# Generated by Django 3.1.2 on 2021-04-22 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortName', models.CharField(max_length=25)),
                ('FullName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('AverageRating', models.FloatField(default=0.0)),
                ('NumberOfRatings', models.IntegerField(default=0)),
                ('Genres', models.CharField(max_length=399)),
                ('MovieLength', models.IntegerField()),
                ('ReleaseDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, default=None, max_length=700, null=True)),
                ('Rating', models.IntegerField()),
                ('RatedAt', models.DateTimeField()),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubeCinema.movie')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FavMovieGenre', models.CharField(max_length=254)),
                ('UserLevel', models.IntegerField(default=0)),
                ('CreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('NumberOfRatings', models.IntegerField(default=0)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
