# Generated by Django 3.1.2 on 2021-04-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubeCinema', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
