# Generated by Django 3.1.2 on 2021-04-28 11:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ClubeCinema', '0002_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, default=None, max_length=700, null=True)),
                ('Rating', models.IntegerField()),
                ('RatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubeCinema.movie')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubeCinema.profile')),
            ],
        ),
    ]
